### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sirnicolaz** [social-dist0rtion-protocol/hunt-zuckerberg#4]
- [ ] Game explanation page: what's the game, how to participate, location of assembly, prices @vrde 
- [x] Ask the user to allow connecting to MetaMask only when needed. @vrde
- [x] Code redeem page: possibly the same page of the game explanation. Field with pre-filled code ready to be redeemed. Once redeemed, zuckerberg piece is shown in the page. @vrde 
- [x] Zuckerberg viewer static: displays the current state of the image based on the unlocked tokens @sirnicolaz
- [x] Zuckerberg viewer: dynamically updates the image once a new token is unlocked @sirnicolaz 
- [ ] Leaderboard: rank of hunters based on number of pieces that have been unlocked
- [x] Deploy script: deploy the content to ipfs and generate a map token => image url
- [x] Puzzle generation: pick zuckerberg picture, decompose it in parts and place each piece on ipfs (unless assets can be deployed automatically while uploading the website to ipfs) @sirnicolaz 
- [x] Hunter summary: given a public key, I know which pieces have been collected
- [x] Hunter verifier: we check public key on user device against transaction public key 
- [ ] End of the game: either they all get unlocked or we unlock the remaining one. We put in the explanation page the public key of the winner.
